services:
  database:
    container_name: product_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB
    ports:
      - '5433:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: {}