version: '3.8'

services:
  database:
    container_name: order_db
    image: mongo:latest 
    restart: always
    environment:
      MONGO_INITDB_DATABASE: $MONGO_DB
    ports:
      - '27018:27017'  
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}